// MINI PROJECT: Limit Order Book
//
// A deliberately small in-memory limit order book -- price-time priority
// matching on both sides, no threading, no persistence. Scoped to what's
// reasonable to write and explain in a short assessment window, not a
// from-scratch HFT engine. See docs/mini_project_research.md for why this
// shape was chosen.
//
// Rules:
// - A Buy order matches against resting Sell orders priced <= its price,
//   cheapest resting sell first (best price), then by submission order
//   among orders at the same price (price-time priority).
// - A Sell order matches against resting Buy orders priced >= its price,
//   highest resting buy first (best price), then by submission order.
// - Any quantity that doesn't fill immediately rests in the book.
// - A single incoming order may generate multiple trades (matching
//   against several resting orders in sequence) if its quantity is larger
//   than any single resting order it crosses.

#pragma once
#include <vector>
#include <optional>

enum class Side { Buy, Sell };

struct Order {
    int id;
    Side side;
    double price;
    int quantity;
};

struct Trade {
    int buy_order_id;
    int sell_order_id;
    double price;    // the resting order's price, not the incoming order's
    int quantity;
};

class OrderBook {
public:
    // Adds a new limit order. If it crosses the spread, matches
    // immediately against resting orders on the opposite side using
    // price-time priority, generating a Trade per match. Any unfilled
    // remainder rests in the book. Returns every trade generated by this
    // call (empty if nothing crossed).
    std::vector<Trade> addLimitOrder(const Order& order);

    // Removes a resting order by id. Returns true if found and removed,
    // false if no such order rests in the book (e.g. already fully filled
    // or never existed).
    bool cancelOrder(int id);

    // Best (highest) resting buy price, or nullopt if no buy orders rest.
    std::optional<double> bestBid() const;

    // Best (lowest) resting sell price, or nullopt if no sell orders rest.
    std::optional<double> bestAsk() const;

private:
    // TODO: pick the data structures. You need, per side:
    //   - orders grouped by price
    //   - within a price, FIFO order (time priority)
    //   - fast lookup by order id for cancelOrder
    // A common shape: std::map<double, std::deque<Order>> per side (map
    // keeps prices sorted, deque preserves arrival order within a price),
    // plus a separate id -> location index for O(1)-ish cancellation.
};
