// MINI PROJECT: Limit Order Book
//
// An in-memory limit order book
// price-time priority
// matching on both sides, no threading, no persistence.
//
// Rules:
// - A Buy order matches against resting Sell orders priced <= its price,
//   cheapest resting sell first (best price), then by submission order
//   among orders at the same price (price-time priority).
// - A Sell order matches against resting Buy orders priced >= its price,
//   highest resting buy first (best price), then by submission order.
// - Any quantity that doesn't fill immediately rests in the book.
// - A single incoming order may generate multiple trades (matching
//   against several resting orders in sequence) if its quantity is larger
//   than any single resting order it crosses.

#pragma once
#include <deque>
#include <map>
#include <vector>
#include <optional>
#include <set>
#include <unordered_map>

enum class Side { Buy, Sell };

// a request to transact(buy/sell) a symbol?
struct Order {
    int id;
    Side side; // what kind of order it is
    double price;
    int quantity; // number of orders

    Order(int id, Side side, double price, int quantity)
        : id(id), side(side), price(price), quantity(quantity) {}
};

// the result of matching two orders
// a trade occurs when the lowest sell price matches the highest buy price
struct Trade {
    int buy_order_id;
    int sell_order_id;
    double price;    // the resting order's price, not the incoming order's
    int quantity;

    Trade(int buy_id, int sell_id, double p, int qty)
        : buy_order_id(buy_id), sell_order_id(sell_id), price(p), quantity(qty) {}
};

class OrderBook {

    // callable from the outside
    public:
    // Adds a new limit order. If it crosses the spread, matches
    // immediately against resting orders on the opposite side using
    // price-time priority, generating a Trade per match. Any unfilled
    // remainder rests in the book. Returns every trade generated by this
    // call (empty if nothing crossed).
    std::vector<Trade> addLimitOrder(const Order& order);

    // Removes a resting order by id. Returns true if found and removed,
    // false if no such order rests in the book (e.g. already fully filled
    // or never existed).
    bool cancelOrder(int id);

    // Best (highest) resting buy price, or nullopt if no buy orders rest.
    std::optional<double> bestBid() const;

    // Best (lowest) resting sell price, or nullopt if no sell orders rest.
    std::optional<double> bestAsk() const;

    // Best (lowest) resting sell price, or nullopt if no sell orders rest.
    bool cancelPrice(double price, Side side);

    Order updateOrder(const Order &order);

    // int process_limit_order(const Order& order);
    // std::pair<Trade, std::optional<Order>> handle_transaction(const Order& buy_order, const Order& sell_order);
    std::optional<Order> process_orders_at_price(Order limit_order, std::set<int> matching_orders);
    // smallest key first by default
    // [10, 11, 20, ...]
    std::map<double, std::set<int>> selling_orders;
    // highest buy price
    // [21, 22, 28, ...]
    std::map<double, std::set<int>> buying_orders;

    std::unordered_map<int, Order> order_index;

    // only accessible from inside class
    private:
    std::vector<Trade> trade_history;

};
